spring.application.name=motor-credito

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/credito}
spring.datasource.username=${DB_USER:creditousr}
spring.datasource.password=${DB_PASSWORD:Credito@}
